<form method="POST" action="{{ $action }}" class="glass-card rounded-2xl p-6 sm:p-8">
    @csrf
    @if($method !== 'POST') @method($method) @endif
    <div class="grid gap-5 sm:grid-cols-2">
        <label class="block"><span class="mb-2 block text-sm font-semibold">Name <span class="text-rose-500">*</span></span><input name="name" value="{{ old('name', $teacher->name) }}" class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm dark:border-white/10 dark:bg-slate-800" required><x-input-error :messages="$errors->get('name')" /></label>
        <label class="block"><span class="mb-2 block text-sm font-semibold">Email <span class="text-rose-500">*</span></span><input type="email" name="email" value="{{ old('email', $teacher->email) }}" class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm dark:border-white/10 dark:bg-slate-800" required><x-input-error :messages="$errors->get('email')" /></label>
        <label class="block sm:col-span-2"><span class="mb-2 block text-sm font-semibold">Assigned classrooms</span><select name="classrooms[]" multiple class="h-40 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm dark:border-white/10 dark:bg-slate-800"><option value="">No classroom assigned</option>@foreach($classrooms as $classroom)<option value="{{ $classroom }}" @selected(in_array($classroom, old('classrooms', $teacher->assignedClassrooms()), true))>{{ $classroom }}</option>@endforeach</select><p class="mt-2 text-xs text-slate-500">Select one or more classrooms for this teacher.</p><x-input-error :messages="$errors->get('classrooms')" /></label>
        <label class="block"><span class="mb-2 block text-sm font-semibold">{{ $teacher->exists ? 'New password' : 'Password' }} <span class="text-rose-500">{{ $teacher->exists ? '' : '*' }}</span></span><input type="password" name="password" class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm dark:border-white/10 dark:bg-slate-800" {{ $teacher->exists ? '' : 'required' }}><x-input-error :messages="$errors->get('password')" /></label>
        <label class="block"><span class="mb-2 block text-sm font-semibold">Confirm password <span class="text-rose-500">{{ $teacher->exists ? '' : '*' }}</span></span><input type="password" name="password_confirmation" class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm dark:border-white/10 dark:bg-slate-800" {{ $teacher->exists ? '' : 'required' }}><x-input-error :messages="$errors->get('password_confirmation')" /></label>
    </div>
    <div class="mt-8 flex flex-wrap justify-end gap-3"><a href="{{ route('teachers.index') }}" class="rounded-xl px-5 py-3 text-sm font-semibold text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800">Cancel</a><button class="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-indigo-500/25 hover:bg-indigo-700">{{ $submit }}</button></div>
</form>
