<form method="POST" action="{{ $action }}" class="glass-card rounded-2xl p-6 sm:p-8">
    @csrf
    @if($method !== 'POST') @method($method) @endif
    <div class="grid gap-5 sm:grid-cols-2">
        <label class="block sm:col-span-2"><span class="mb-2 block text-sm font-semibold">LAN <span class="text-rose-500">*</span></span><input name="lan" value="{{ old('lan', $child?->lan) }}" class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm focus:border-indigo-500 focus:ring-indigo-500 dark:border-white/10 dark:bg-slate-800" required><x-input-error :messages="$errors->get('lan')" /></label>
        <label class="block"><span class="mb-2 block text-sm font-semibold">First name <span class="text-rose-500">*</span></span><input name="first_name" value="{{ old('first_name', $child?->first_name) }}" class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm focus:border-indigo-500 focus:ring-indigo-500 dark:border-white/10 dark:bg-slate-800" required><x-input-error :messages="$errors->get('first_name')" /></label>
        <label class="block"><span class="mb-2 block text-sm font-semibold">Last name <span class="text-rose-500">*</span></span><input name="last_name" value="{{ old('last_name', $child?->last_name) }}" class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm focus:border-indigo-500 focus:ring-indigo-500 dark:border-white/10 dark:bg-slate-800" required><x-input-error :messages="$errors->get('last_name')" /></label>
        <label class="block"><span class="mb-2 block text-sm font-semibold">Date of birth</span><input type="date" name="dob" value="{{ old('dob', $child?->dob?->format('Y-m-d')) }}" class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm dark:border-white/10 dark:bg-slate-800"><x-input-error :messages="$errors->get('dob')" /></label>
        <label class="block"><span class="mb-2 block text-sm font-semibold">Age</span><input type="number" min="0" max="18" name="age" value="{{ old('age', $child?->age) }}" class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm dark:border-white/10 dark:bg-slate-800"><x-input-error :messages="$errors->get('age')" /></label>
        <label class="block"><span class="mb-2 block text-sm font-semibold">Classroom <span class="text-rose-500">*</span></span><input name="classroom" value="{{ old('classroom', $child?->classroom) }}" placeholder="e.g. Preschool" class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm dark:border-white/10 dark:bg-slate-800" required><x-input-error :messages="$errors->get('classroom')" /></label>
        <label class="block"><span class="mb-2 block text-sm font-semibold">Status <span class="text-rose-500">*</span></span><select name="status" class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm dark:border-white/10 dark:bg-slate-800">@foreach(['Active', 'Inactive'] as $status)<option value="{{ $status }}" @selected(old('status', $child?->status ?? 'Active') === $status)>{{ $status }}</option>@endforeach</select><x-input-error :messages="$errors->get('status')" /></label>
    </div>
    <div class="mt-8 flex flex-wrap justify-end gap-3"><a href="{{ route('children.index') }}" class="rounded-xl px-5 py-3 text-sm font-semibold text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800">Cancel</a><button class="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-indigo-500/25 hover:bg-indigo-700">{{ $submit }}</button></div>
</form>
