<form method="POST" action="{{ $action }}" class="glass-card rounded-2xl p-6 sm:p-8">
    @csrf
    @if($method !== 'POST') @method($method) @endif
    @php($extracted = session('extracted_child', []))
    <div class="grid gap-5 sm:grid-cols-2">
        <label class="block sm:col-span-2"><span class="mb-2 block text-sm font-semibold">LAN <span class="text-rose-500">*</span></span><input name="lan" value="{{ old('lan', $child?->lan) }}" class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm focus:border-indigo-500 focus:ring-indigo-500 dark:border-white/10 dark:bg-slate-800" required><x-input-error :messages="$errors->get('lan')" /></label>
        <label class="block sm:col-span-2"><span class="mb-2 block text-sm font-semibold">Child Name</span><input name="child_name" value="{{ old('child_name', $child?->child_name ?? ($extracted['child_name'] ?? '')) }}" class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm dark:border-white/10 dark:bg-slate-800"><x-input-error :messages="$errors->get('child_name')" /></label>
        <label class="block"><span class="mb-2 block text-sm font-semibold">First name <span class="text-rose-500">*</span></span><input name="first_name" value="{{ old('first_name', $child?->first_name ?? ($extracted['first_name'] ?? '')) }}" class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm focus:border-indigo-500 focus:ring-indigo-500 dark:border-white/10 dark:bg-slate-800" required><x-input-error :messages="$errors->get('first_name')" /></label>
        <label class="block"><span class="mb-2 block text-sm font-semibold">Last name <span class="text-rose-500">*</span></span><input name="last_name" value="{{ old('last_name', $child?->last_name ?? ($extracted['last_name'] ?? '')) }}" class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm focus:border-indigo-500 focus:ring-indigo-500 dark:border-white/10 dark:bg-slate-800" required><x-input-error :messages="$errors->get('last_name')" /></label>
        <label class="block"><span class="mb-2 block text-sm font-semibold">Age</span><input id="age" type="text" name="age" value="{{ old('age', $child?->age) }}" placeholder="e.g. 1 year and 3 months" class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm dark:border-white/10 dark:bg-slate-800"><x-input-error :messages="$errors->get('age')" /></label>
        <label class="block"><span class="mb-2 block text-sm font-semibold">Classroom <span class="text-rose-500">*</span></span><input name="classroom" value="{{ old('classroom', $child?->classroom) }}" placeholder="e.g. Preschool" class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm dark:border-white/10 dark:bg-slate-800" required><x-input-error :messages="$errors->get('classroom')" /></label>
        <label class="block"><span class="mb-2 block text-sm font-semibold">Status <span class="text-rose-500">*</span></span><select name="status" class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm dark:border-white/10 dark:bg-slate-800">@foreach(['Active', 'Inactive'] as $status)<option value="{{ $status }}" @selected(old('status', $child?->status ?? 'Active') === $status)>{{ $status }}</option>@endforeach</select><x-input-error :messages="$errors->get('status')" /></label>
    </div>
    @php($sections = [
        'Child details' => ['Nickname' => 'nickname', 'Address' => 'address', 'City' => 'city', 'Zip' => 'zip', 'Telephone' => 'telephone', 'Birth Date' => 'birth_date', 'Parents Status' => 'parents_status', 'Responsible for Payment' => 'responsible_for_payment'],
        'Mother / Legal Guardian' => ['Mother Name' => 'mother_name', 'Mother Address' => 'mother_address', 'Mother Home Phone' => 'mother_home_phone', 'Mother Employer' => 'mother_employer', 'Mother Work Phone' => 'mother_work_phone', 'Mother Fax' => 'mother_fax', 'Mother Cell' => 'mother_cell', 'Mother Email' => 'mother_email', 'Mother Title' => 'mother_title', 'Mother SSN' => 'mother_ssn'],
        'Father / Legal Guardian' => ['Father Name' => 'father_name', 'Father Address' => 'father_address', 'Father Home Phone' => 'father_home_phone', 'Father Employer' => 'father_employer', 'Father Work Phone' => 'father_work_phone', 'Father Fax' => 'father_fax', 'Father Cell' => 'father_cell', 'Father Email' => 'father_email', 'Father Title' => 'father_title', 'Father SSN' => 'father_ssn'],
        'Emergency contacts' => ['Emergency Contact' => 'emergency_contact', 'Secondary Emergency Contact' => 'secondary_emergency_contact', 'Emergency Telephone' => 'emergency_telephone', 'Emergency Relationship' => 'emergency_relationship', 'Emergency License #' => 'emergency_license_number'],
        'Authorized Pickup 1' => ['Pickup 1 Name' => 'pickup_1_name', 'Pickup 1 Address' => 'pickup_1_address', 'Pickup 1 Telephone' => 'pickup_1_telephone', 'Pickup 1 Alternate' => 'pickup_1_alternate', 'Pickup 1 Relationship' => 'pickup_1_relationship', 'Pickup 1 License #' => 'pickup_1_license_number'],
        'Authorized Pickup 2' => ['Pickup 2 Name' => 'pickup_2_name', 'Pickup 2 Address' => 'pickup_2_address', 'Pickup 2 Telephone' => 'pickup_2_telephone', 'Pickup 2 Alternate' => 'pickup_2_alternate', 'Pickup 2 Relationship' => 'pickup_2_relationship', 'Pickup 2 License #' => 'pickup_2_license_number'],
        'Authorized Pickup 3' => ['Pickup 3 Name' => 'pickup_3_name', 'Pickup 3 Address' => 'pickup_3_address', 'Pickup 3 Telephone' => 'pickup_3_telephone', 'Pickup 3 Alternate' => 'pickup_3_alternate', 'Pickup 3 Relationship' => 'pickup_3_relationship', 'Pickup 3 License #' => 'pickup_3_license_number'],
    ])
    @foreach($sections as $heading => $fields)
        <section class="mt-8 border-t border-slate-200 pt-7 dark:border-white/10"><h2 class="mb-5 text-lg font-bold">{{ $heading }}</h2><div class="grid gap-5 sm:grid-cols-2">@foreach($fields as $label => $field)<label class="block {{ str_contains($field, 'address') ? 'sm:col-span-2' : '' }}"><span class="mb-2 block text-sm font-semibold">{{ $label }}</span><input id="{{ $field }}" type="{{ $field === 'birth_date' ? 'date' : 'text' }}" name="{{ $field }}" value="{{ old($field, data_get($child, $field) ?? ($extracted[$field] ?? '')) }}" class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm dark:border-white/10 dark:bg-slate-800"><x-input-error :messages="$errors->get($field)" /></label>@endforeach</div></section>
    @endforeach
    <section class="mt-8 border-t border-slate-200 pt-7 dark:border-white/10"><h2 class="mb-5 text-lg font-bold">Notes</h2><div class="grid gap-5"><label><span class="mb-2 block text-sm font-semibold">Other Notes</span><textarea name="other_notes" rows="3" class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm dark:border-white/10 dark:bg-slate-800">{{ old('other_notes', $child?->other_notes ?? ($extracted['other_notes'] ?? '')) }}</textarea></label><label><span class="mb-2 block text-sm font-semibold">Important Notes</span><textarea name="important_notes" rows="3" class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm dark:border-white/10 dark:bg-slate-800">{{ old('important_notes', $child?->important_notes ?? ($extracted['important_notes'] ?? '')) }}</textarea></label></div></section>
    <script>
        (() => { const birth = document.getElementById('birth_date'), age = document.getElementById('age'); if (!birth || !age) return; const updateAge = () => { if (!birth.value || age.value) return; const today = new Date(), date = new Date(`${birth.value}T00:00:00`); let years = today.getFullYear() - date.getFullYear(), months = today.getMonth() - date.getMonth(); if (today.getDate() < date.getDate()) months--; if (months < 0) { years--; months += 12; } if (years < 0) return; age.value = years ? `${years} ${years === 1 ? 'year' : 'years'}${months ? ` and ${months} ${months === 1 ? 'month' : 'months'}` : ''}` : `${months} ${months === 1 ? 'month' : 'months'}`; }; birth.addEventListener('change', updateAge); updateAge(); })();
    </script>
    <div class="mt-8 flex flex-wrap justify-end gap-3"><a href="{{ route('children.index') }}" class="rounded-xl px-5 py-3 text-sm font-semibold text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800">Cancel</a><button class="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-indigo-500/25 hover:bg-indigo-700">{{ $submit }}</button></div>
</form>
