@extends('layouts.app')
@section('title', 'Children')
@section('content')
<div x-data="{ search: '' }">
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
        <x-page-header :title="auth()->user()->isAdmin() ? 'Children' : 'My Students'" :subtitle="auth()->user()->isAdmin() ? 'Manage your daycare roster and classroom assignments.' : 'Students assigned to your classroom.'"/>
        @if(auth()->user()->isAdmin())<a href="{{ route('children.create') }}" class="inline-flex w-fit items-center gap-2 rounded-xl bg-indigo-600 px-4 py-3 text-sm font-semibold text-white shadow-lg shadow-indigo-500/25 hover:bg-indigo-700">+ Add Child</a>@endif
    </div>
    @if(session('success'))<div class="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">{{ session('success') }}</div>@endif
    @php($nextDirection = fn ($column) => $sort === $column && $direction === 'asc' ? 'desc' : 'asc')
    @php($sortUrl = fn ($column) => route('children.index', ['sort' => $column, 'direction' => $nextDirection($column)]))
    @php($arrow = fn ($column) => $sort === $column ? ($direction === 'asc' ? ' ↑' : ' ↓') : '')
    <section class="glass-card mt-7 overflow-hidden rounded-2xl">
        <div class="border-b border-slate-100 p-4 dark:border-white/10"><input x-model="search" class="w-full rounded-xl border-0 bg-slate-100 px-4 py-3 text-sm ring-1 ring-slate-200 focus:ring-2 focus:ring-indigo-500 dark:bg-slate-800 dark:ring-white/10" placeholder="Search children by name, classroom, or LAN..."></div>
        <div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500 dark:bg-slate-800/60"><tr><th class="px-6 py-4 font-semibold"><a href="{{ $sortUrl('lan') }}">LAN{{ $arrow('lan') }}</a></th><th class="px-6 py-4 font-semibold"><a href="{{ $sortUrl('last_name') }}">Child{{ $arrow('last_name') }}</a></th><th class="px-6 py-4 font-semibold"><a href="{{ $sortUrl('age') }}">Age{{ $arrow('age') }}</a></th><th class="px-6 py-4 font-semibold"><a href="{{ $sortUrl('classroom') }}">Classroom{{ $arrow('classroom') }}</a></th><th class="px-6 py-4 font-semibold"><a href="{{ $sortUrl('status') }}">Status{{ $arrow('status') }}</a></th><th class="px-6 py-4 font-semibold">Actions</th></tr></thead>
        <tbody class="divide-y divide-slate-100 dark:divide-white/10">@forelse($children as $child)<tr x-show="@js(strtolower($child->first_name.' '.$child->last_name.' '.$child->classroom.' '.$child->lan)).includes(search.toLowerCase())" class="hover:bg-slate-50/80 dark:hover:bg-white/5"><td class="px-6 py-4 text-slate-500">{{ $child->lan }}</td><td class="px-6 py-4"><div class="flex items-center gap-3"><span class="grid h-9 w-9 place-items-center rounded-full bg-indigo-100 font-bold text-indigo-700">{{ strtoupper(substr($child->first_name,0,1)) }}</span><span class="font-semibold">{{ $child->first_name }} {{ $child->last_name }}</span></div></td><td class="px-6 py-4"><span class="font-medium">{{ $child->ageLabel() ?? '—' }}</span>@if($child->birthDate())<span class="block text-xs text-slate-400 dark:text-slate-500">Born {{ $child->birthDate()->format('M j, Y') }}</span>@endif</td><td class="px-6 py-4">{{ $child->classroom }}</td><td class="px-6 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $child->status === 'Active' ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-200 text-slate-600' }}">{{ $child->status }}</span></td><td class="px-6 py-4">@if(auth()->user()->isAdmin())<a href="{{ route('children.edit', $child) }}" class="font-semibold text-indigo-600 hover:text-indigo-800">Edit</a>@else<span class="text-slate-400">View only</span>@endif</td></tr>@empty<tr><td colspan="6" class="px-6 py-12 text-center text-slate-500">No children have been added yet.</td></tr>@endforelse</tbody></table></div>
    </section>
</div>
@endsection
